### ISSUE TITLE
[component] 헤더

### ISSUE THREAD

**Issue by Jess-Apr** [Team-Maltesers/DayGrid#4]
### To-do
- [x] 로고, 이름, 햄버거 메뉴
- [x] 햄버거 메뉴 클릭 시 메뉴 모달 오픈
- [x] 비로그인 시 로그인, 회원가입 버튼 노출
- [x] 로그인 시 햄버거 메뉴 노출
